### ISSUE TITLE
Unable to move from Neovim (LunarVim) back to Kitty

### ISSUE THREAD

**Issue by megawubs** [MunsMan/kitty-navigator.nvim#1]
Hi,

I've installed this plugin and put the required python files in the correct location. Navigating between kitty splits works now. But whenever I'm inside a Neovim window, it does not navigate back to kitty. Navigation between splits inside neovim works. I just can't get back to kitty when i'm at the last split

**Comment by MunsMan** [comment]
I'm sorry to hear about the issue you're experiencing. Based on your description, it seems there might be two potential causes for the malfunction:
1. An error in detecting the last window.
2. An issue when moving out of Neovim.

Since I'm unable to reproduce the error on my end, troubleshooting it directly is a bit challenging. If you're up for it, you could create a minimal configuration that replicates the problem, and then I can help debug it more effectively.

Alternatively, you might want to try debugging it on your end. I recommend starting by verifying if the `kitty` terminal's API is accessible from your setup. You can test this by executing the following command:
```
kitty @ kitten navigate_kitty.py <direction>
```
Replace `<direction>` with `left`, `right`, `up`, or `down` to see if it correctly moves to the next split in the specified direction.

If this test succeeds, the next step would be to check for any issues in Neovim’s window management logic. This is particularly intriguing as I have not encountered this issue before.

Please let me know how these steps go, and I’ll assist further based on your findings.

**Comment by megawubs** [comment]
Thank you for your time and explanation on how to test this.

I've tested `kitty @ kitten navigate_kitty.py left` with a split like this:
```
|--------|-----|
|lunarvim|kitty|
|--------|-----|
```

This works with `kitty @ kitten navigate_kitty.py left`
```
|--------|---------|
|lunarvim|<-- kitty|
|--------|---------|
```

It only started working after I enabled remote control in my `~/.config/kitty/kitty.conf` file:

```
allow_remote_control yes
```


But I'm unable to test this:
```
|------------|-----|
|lunarvim -->|kitty|
|------------|-----|
```

I've tried it with the default keymapping: `<C-l>` and with `:lua require("kitty-navigator").navigateRight()`

Do you have any idea how to debug this from within neovim?

**Comment by MunsMan** [comment]
Thank you for providing such a detailed explanation.

It appears that we might be missing some critical configuration settings in the `kitty.conf` file that are necessary for remote control, which haven't yet been documented in our README. Please ensure you include the following settings:

For Linux:
```conf
# For linux only:
allow_remote_control yes
listen_on unix:@mykitty
```

For other Unix systems:
```conf
# Other unix systems:
allow_remote_control yes
listen_on unix:/tmp/mykitty
```

I will update the README to include these configurations to assist future users.

If adding these configurations doesn't resolve the issue, we can proceed with debugging the problem directly from within Neovim. You can do this by executing the following Neovim command which calls the kitty API:
```vim
:lua vim.fn.system("kitty @ kitten navigate_kitty.py <direction>")
```
Replace `<direction>` with the appropriate direction (`left`, `right`, `up`, or `down`) to test moving between splits.

Please try these steps and let me know if you encounter further issues. I’m here to help!

**Comment by megawubs** [comment]
`listen_on unix:/tmp/mykitty` and a restart of kitty was what I needed! Just reloading the config was not enough. Thank you for helping me out!
